### ISSUE TITLE
tracking issue: initial version

### ISSUE THREAD

**Issue by NOBLES5E** [PersiaML/PERSIA#7]
Documentation: @karoka 
- [ ] Tutorials
  - [x] Introduction
  - [x] Installation @williamstar 
  - [x] Getting Started @williamstar 
  - [x] Benchmark (experiments * 3)
    - [x] XDL @snowpeakz 
    - [x] Paddle @snowpeakz 
  - [x] Data processing @snowpeakz 
  - [x] Monitoring @snowpeakz 
  - [x] Inference @snowpeakz 
  - [x] Model checkpointing @williamstar 
  - [x] Configuration @snowpeakz 
  - [x] Troubleshooting @williamstar 
  - [x] Kubernetes Integration @williamstar 
  - [ ] Advanced: @williamstar 
  	- [ ] Raw embedding
  	- [ ] HashStack
  	- [ ] Separate data loader
- [x] API documentation @williamstar  https://persiaml.pages.dev/
- [x] add system test (with buildkite)
	- [x] train, test (assert number of samples, train and test auc etc.) @williamstar 
	- [x] load, dump @snowpeakz 
	- [x] inference @snowpeakz 
	- [x] move e2e test script to examples @williamstar 

----
Bug:
- [x] 	persia-core PyForward && PyBackward thread handler exit with exceptions
- [x]	insert embedding in offline inference phase

----
Feature:
- [x] python launcher @williamstar 
- [x] cpu backward with gloo backend @williamstar 
- [x] ddp launch with tcp to replace env_file @snowpeakz 
- [x] support epoch level dataloader @williamstar 
- [x] easy pip install persiaml @williamstar 
- [x] unified storage trait, saving both dense & sparse parameters @snowpeakz 
- [ ] support s3 @williamstar 

----
Experiments:
- [x] Single card + force enable communication
- [x] Change figure titles

----
Release

- [x] merge server code with python code @NOBLES5E 
- [ ] GitHub releases @williamstar 
- [x] all persia container images @williamstar 
- [x] kubernetes operator @williamstar 

----
- [x] NATS integration @snowpeakz 
- [x] multi-node multi-card usable demo @williamstar 
- [x] fix remaining bugs (like in data processing) @williamstar 
- [x] publish PyPI wheels on CI @NOBLES5E 
- [x] API documentation website @NOBLES5E

**Comment by williamstar** [comment]
- ` multi-node multi-card usable demo` need to launch with `docker service create` to assign gpu resource
